from typing import Dict


CURRENCY_SIGILS: Dict[str, str] = {
    "CAD": "$",
    "EUR": "€",
    "GBP": "£",
    "USD": "$",
    "ARS": "$",
    "AFN": "؋",    # right
    "AED": "د.إ",  # right
    "AUD": "$",
    "AZN": "₼",
    "BAM": "KM",
    "BBD": "$",
    # "BDT": "",
    "BGN": "лв",
    # "BIF": "",
    "BMD": "$",
    "BND": "$",
    "BOB": "$b",
    "BRL": "R$",
    "BSD": "$",
    "BWP": "P",
    "BYN": "Br",
    "BZD": "BZ$",
    # "CDF": "",
    "CHF": "Fr",  # right
    "CLP": "$",
    "CNY": "¥",
    "COP": "$",
    "CRC": "₡",
    # "CVE": "",
    "CZK": "Kč",
    # "DJF": "",
    "DKK": "kr",
    "DOP": "RD$",
    # "DZD": "",
    "EGP": "£",
    # "ETB": "",
    "FJD": "$",
    "FKP": "£",
    "GEL": "₾",
    "GIP": "£",
    "GMD": "D",
    "GNF": "FG",
    "GTQ": "Q",
    "GYD": "$",
    "HKD": "$",
    "HNL": "L",
    "HRK": "kn",
    "HTG": "G",
    "HUF": "Ft",
    "IDR": "Rp",
    "ILS": "₪",
    "INR": "₹",
    "ISK": "kr",  # right
    "JMD": "J$",
    "JPY": "¥",
    "KES": "KSh",
    "KGS": "лв",
    "KHR": "៛",
    "KMF": "CF",
    "KRW": "₩",
    "KYD": "$",
    "KZT": "₸",
    "LAK": "₭",
    "LBP": "ل.ل.",  # right
    "LKR": "₨",
    "LRD": "L$",
    # "LSL": "",
    # "MAD": "",
    # "MDL": "",
    "MGA": "Ar",
    "MKD": "ден",
    "MMK": "K",
    "MNT": "₮",
    "MOP": "MOP$",
    "MRU": "UM",
    "MUR": "₨",
    # "MVR": "",
    "MWK": "MK",
    "MXN": "$",
    "MYR": "RM",
    "MZN": "MT",
    "NAD": "$",
    "NGN": "₦",
    "NIO": "C$",
    "NOK": "kr",  # right
    "NPR": "₨",
    "NZD": "$",
    "PAB": "B/.",
    "PEN": "S/.",
    "PGK": "K",
    "PHP": "₱",
    "PKR": "₨",
    "PLN": "zł",  # right
    "PYG": "₲",
    "QAR": "﷼",  # right
    "RON": "lei",
    "RSD": "РСД",
    "RUB": "₽",
    # "RWF": "",
    "SAR": "﷼",  # right
    "SBD": "$",
    "SCR": "₨",
    "SEK": "kr",  # right
    "SGD": "$",
    "SHP": "£",
    "SLL": "Le",
    "SOS": "S",
    "SRD": "$",
    "STN": "Db",
    # "SZL": "",
    "THB": "฿",
    "TJS": "ЅM",
    "TOP": "T$",
    "TRY": "₺",
    "TTD": "TT$",
    "TWD": "NT$",
    # "TZS": "",
    "UAH": "₴",
    "UGX": "USh",
    "UYU": "$U",
    # "UZS": "",
    "VND": "₫",
    "VUV": "VT",
    "WST": "$",
    # "XAF": "",
    "XCD": "$",
    # "XOF": "",
    # "XPF": "",
    "YER": "﷼",  # right
    "ZAR": "R",
    "ZMW": "ZK",
}


RIGHT_SIDE_SIMBOLS = (
    "AFN",
    "AED",
    "CHF",
    "ISK",
    "LBP",
    "NOK",
    "PLN",
    "QAR",
    "SAR",
    "SEK",
    "YER",
)
