# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2
mkdocs:
  configuration: mkdocs.yml

python:
<<<<<<< HEAD
  version: "3.11"
=======
  version: 3.9
>>>>>>> 0538a0cd (Test to see if docs works on my branch)
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
