# Please read the inline comments to know what to comment out and what not to comment out to run
# various db backends

version: "3.9"

# can be commented out when using sqlite
volumes:
    # sqlite doesn't require persistence as it is an in-memory db anyway
    postgres-data: {}
    mysql-data: {}

services:

  db:


    image: postgres:12
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=random_number
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=random_number


    # image: mysql:5.7
    # # command: --default-authentication-plugin=mysql_native_password
    # volumes:
    #   - mysql-data:/var/lib/mysql
    # environment:
    #   - MYSQL_DATABASE=random_number
    #   # - MYSQL_USER=random_number
    #   # - MYSQL_PASSWORD=random_number
    #   - MYSQL_ROOT_PASSWORD=random_number

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - "./poetry.lock:/app/poetry.lock"
    ports:
      - "8000:8000"
      # 5678 is a common python debugging port (using in manage.py for debugpy)
      - "5678:5678"
      # 5679 is another python debugging port (using in djstripe_sync_models.py for debugpy)
      - "5679:5679"
    # can be commented out when using sqlite
    depends_on:
      - db
    environment:
    ##############################################
        # # Stripe specific keys (Do not comment)
        - STRIPE_PUBLIC_KEY=pk_test_51ItQ7cJSZQVUcJYgoSx1ZdKy5zhybSUiyJXWQno83L24EPUlFHeIe2QVe1RiB7kxvbjJ9SZ0G6R3fnfJTamauH1C00MyCpOqZ8
        # djstripe
        - STRIPE_SECRET_KEY=sk_test_51ItQ7cJSZQVUcJYgHMIKKvkqL6XNUHRI1kQcpoR9yEdOusA5rWpTXpXYnIqHpIvWlu5odQYNBDVwNSYTJN1HmtCC00RvEyLiZW
        # # For UUID: 1c77437a-1692-4f4d-bb13-8accf9509181
        - DJSTRIPE_TEST_WEBHOOK_SECRET=whsec_5wNQQwYbfwgVsGOXhPAId44UnAp6SYMc



        # # # For UUID: b04655e4-6dc9-4f6b-bbaa-72d553dba648
        # - DJSTRIPE_TEST_WEBHOOK_SECRET=whsec_atrQHypckSRYBOG2GAblEod47bPDJ0p2


        # # # For UUID: 2247007f-a917-4cbf-a94a-e45a7934ca37
        # - DJSTRIPE_TEST_WEBHOOK_SECRET=whsec_JuD2BGuVv9veVPJspO4l0mQfblPEqZ2p

        # # # For UUID: 0bef45ee-10ab-47a8-9d2b-f5451da5dae2
        # - DJSTRIPE_TEST_WEBHOOK_SECRET=whsec_kPQjj06VD4CgxVnvlMG1sXoOZf5k9iY9
        # # personal
        # - STRIPE_API_KEY=sk_test_51Fg9jUA3kq9o1aTczzVzC3jP1gU0BTsx8YfnOOzG3B6eL1BIcQcgSTBpqnmX3dCHIB58pyKr19YB6xT7tMLGEEj200mXR3NHUu
    ##############################################
        # # Uncomment to run sqlite db (everything below can be commented out)
        # - DJSTRIPE_TEST_DB_VENDOR=sqlite
    ##############################################
        # # uncomment the following 3 when using postgresql db
        - DJSTRIPE_TEST_DB_VENDOR=postgres
        - DJSTRIPE_TEST_DB_PORT=5432
        - DJSTRIPE_TEST_DB_USER=root
    ##############################################
        # # uncomment the following 3 when using mysql db
        # - DJSTRIPE_TEST_DB_VENDOR=mysql
        # - DJSTRIPE_TEST_DB_PORT=3306
        # # - DJSTRIPE_TEST_DB_USER=random_number
    ##############################################
        # # do not comment as it is the same for both postgresql and mysql
        # # can be commented out for sqlite
        - DJSTRIPE_TEST_DB_NAME=random_number
        - DJSTRIPE_TEST_DB_PASS=random_number
        - DJSTRIPE_TEST_DB_HOST=db

# ! x-djstripe-webhook-secret needs to be set equal to the output of `Stripe CLI` for local webhook testing.
  stripe:
    image: stripe/stripe-cli:v1.13.6
    # new with uuid (for dj-stripe)
    command: ["listen", "-H", "x-djstripe-webhook-secret: whsec_41a30547f3aa245031507ab2b4898a07904bbf4c02b09b52b8d375412b0d9530", "--forward-to", "http://web:8000/djstripe/webhook/6be37840-dbc4-4646-9240-e78f5cf71439/"]
    # # new with uuid (for Personal)
    # command: ["listen", "-H", "x-djstripe-webhook-secret: whsec_41a30547f3aa245031507ab2b4898a07904bbf4c02b09b52b8d375412b0d9530", "--forward-to", "http://web:8000/djstripe/webhook/b1e24d53-cba6-4658-bea1-e5233b1dc004/"]

    # # old without uuid
    # command: ["listen", "-H", "x-djstripe-webhook-secret: whsec_41a30547f3aa245031507ab2b4898a07904bbf4c02b09b52b8d375412b0d9530", "--forward-to", "http://web:8000/djstripe/webhook/"]

    depends_on:
      - web
    environment:
      # djstripe
      - STRIPE_API_KEY=sk_test_51ItQ7cJSZQVUcJYgHMIKKvkqL6XNUHRI1kQcpoR9yEdOusA5rWpTXpXYnIqHpIvWlu5odQYNBDVwNSYTJN1HmtCC00RvEyLiZW
      # # personal
      # - STRIPE_API_KEY=sk_test_51Fg9jUA3kq9o1aTczzVzC3jP1gU0BTsx8YfnOOzG3B6eL1BIcQcgSTBpqnmX3dCHIB58pyKr19YB6xT7tMLGEEj200mXR3NHUu
      - STRIPE_DEVICE_NAME=djstripe_imac_docker
