# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0001_initial"),
    ]

    operations = [
        # Step 1: Create a `customer_from_source` field on Card.
        migrations.AddField(
            model_name="card",
            name="customer_from_source",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="sources", to="djstripe.Customer"),
        ),
        # Step 2: Backfill `customer_from_source` using data from the parent source model.
        migrations.RunSQL("""
            UPDATE djstripe_card AS dc
            SET customer_from_source_id = ds.customer_id
            FROM djstripe_stripesource AS ds
            WHERE dc.stripesource_ptr_id = ds.id
        """),
        # Step 3: Drop `customer` on parent source model.
        migrations.RemoveField(
            model_name="stripesource",
            name="customer",
        ),
        # Step 4: Rename `customer_from_source` to `customer`.
        migrations.RenameField(
            model_name="card",
            old_name="customer_from_source",
            new_name="customer",
        ),
        # Step 5: Drop NULL on `card.customer`
        migrations.AlterField(
            model_name="card",
            name="customer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sources", to="djstripe.Customer"),
        ),
    ]
