# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-26 17:16
from __future__ import unicode_literals

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deactivate_on',
            field=djstripe.fields.StripeJSONField(help_text='An array of connect application identifiers that cannot purchase this product. Only applicable to products of `type=good`.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=djstripe.fields.StripeJSONField(help_text='A list of up to 8 URLs of images for this product, meant to be displayable to the customer. Only applicable to products of `type=good`.', null=True),
        ),
    ]
