# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0001_initial"),
    ]

    operations = [
        # Step 1: Create a `customer_from_source` field on Card.
        migrations.AddField(
            model_name="card",
            name="customer_from_source",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="sources", to="djstripe.Customer"),
        ),
        # Step 2: Backfill `customer_from_source` using data from the parent source model.
        migrations.RunSQL("""
            UPDATE djstripe_card AS dc
            SET customer_from_source_id = ds.customer_id
            FROM djstripe_stripesource AS ds
            WHERE dc.stripesource_ptr_id = ds.id
        """),
        # Step 3: Drop `customer` on parent source model.
        migrations.RemoveField(
            model_name="stripesource",
            name="customer",
        ),
        # Step 4: Rename `customer_from_source` to `customer`.
        migrations.RenameField(
            model_name="card",
            old_name="customer_from_source",
            new_name="customer",
        ),
        # Step 5: Drop NULL on `card.customer`
        migrations.AlterField(
            model_name="card",
            name="customer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sources", to="djstripe.Customer"),
        ),

        # Step 6: Add a PaymentMethod model
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                ("id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("type", models.CharField(db_index=True, max_length=12)),
            ],
        ),
        # Step 7: Backfill the PaymentMethod model, using data from the Card table
        # The neat thing: We don"t have to worry about handling non-card data because
        # until now, it was not supported in djstripe.
        migrations.RunSQL("""
            INSERT INTO djstripe_paymentmethod (id, type)
                SELECT stripe_id, 'card'
                FROM djstripe_stripesource
        """),

        # Step 8: Rename `charge.source` and `customer.default_source` to `_old` prefix
        migrations.RenameField(
            model_name="charge",
            old_name="source",
            new_name="source_old",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="default_source",
            new_name="default_source_old",
        ),

        # Step 9: Add `charge.source` and `customer.default_source` fields
        # They will be ForeignKeys to the PaymentMethod model
        migrations.AddField(
            model_name="charge",
            name="source",
            field=djstripe.fields.PaymentMethodForeignKey(help_text="The source used for this charge.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="charges", to="djstripe.PaymentMethod"),
        ),
        migrations.AddField(
            model_name="customer",
            name="default_source",
            field=djstripe.fields.PaymentMethodForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="customers", to="djstripe.PaymentMethod"),
        ),

        # Step 10: Backfill `charge.source` and `customer.default_source`
        # The values are the stripe IDs of the sources.
        migrations.RunSQL("""
            UPDATE djstripe_charge AS dch
            SET source_id = dss.stripe_id
            FROM djstripe_stripesource AS dss
            WHERE dch.source_old_id = dss.id
        """),
        migrations.RunSQL("""
            UPDATE djstripe_customer AS dcu
            SET default_source_id = dss.stripe_id
            FROM djstripe_stripesource AS dss
            WHERE dcu.default_source_old_id = dss.id
        """),

        # Step 11: Drop the `_old` fields.
        migrations.RemoveField(
            model_name="charge",
            name="source_old",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="default_source_old",
        ),
    ]
