# Generated by Django 2.1.2 on 2018-11-01 09:20

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0002_auto_20180627_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=djstripe.fields.StripeJSONField(blank=True, help_text='A list of up to 5 attributes that each SKU can provide values for (e.g., `["color", "size"]`). Only applicable to products of `type=good`.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='caption',
            field=djstripe.fields.StripeCharField(blank=True, help_text='A short one-line description of the product, meant to be displayableto the customer. Only applicable to products of `type=good`.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='deactivate_on',
            field=djstripe.fields.StripeJSONField(blank=True, help_text='An array of connect application identifiers that cannot purchase this product. Only applicable to products of `type=good`.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=djstripe.fields.StripeJSONField(blank=True, help_text='A list of up to 8 URLs of images for this product, meant to be displayable to the customer. Only applicable to products of `type=good`.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='package_dimensions',
            field=djstripe.fields.StripeJSONField(blank=True, help_text='The dimensions of this product for shipping purposes. A SKU associated with this product can override this value by having its own `package_dimensions`. Only applicable to products of `type=good`.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_label',
            field=djstripe.fields.StripeCharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=djstripe.fields.StripeCharField(blank=True, help_text='A URL of a publicly-accessible webpage for this product. Only applicable to products of `type=good`.', max_length=799, null=True),
        ),
    ]
