# Generated by Django 4.1.4 on 2023-09-06 08:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0002_account_djstripe_data_apikey_djstripe_data_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="webhookendpoint",
            old_name="tolerance",
            new_name="djstripe_tolerance",
        ),
    ]
