# Generated by Django 2.1.3 on 2018-11-19 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0002_auto_20180627_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account',
            field=models.ForeignKey(help_text='The account the charge was made on behalf of. Null here indicates that this value was never set.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_account', to='djstripe.Account'),
        ),
    ]
