# Generated by Django 2.2.2 on 2019-06-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("djstripe", "0003_auto_20181117_2328_squashed_0004_auto_20190227_2114")
	]

	operations = [
		migrations.AlterField(
			model_name="subscriptionitem",
			name="quantity",
			field=models.PositiveIntegerField(
				blank=True,
				help_text="The quantity of the plan to which the customer should be subscribed.",
				null=True,
			),
		)
	]
