# Generated by Django 2.1.7 on 2019-03-06 16:44

from django.db import migrations
import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0003_auto_20181117_2328_squashed_0004_auto_20190227_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='billing',
            field=djstripe.fields.StripeEnumField(enum=djstripe.enums.InvoiceBilling, help_text='When charging automatically, Stripe will attempt to pay this invoice using the default source attached to the customer. When sending an invoice, Stripe will email this invoice to the customer with payment instructions.', max_length=20, null=True),
        ),
    ]
