# Generated by Django 4.1.4 on 2023-09-06 08:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0003_rename_tolerance_webhookendpoint_djstripe_tolerance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="webhookendpoint",
            old_name="validation_method",
            new_name="djstripe_validation_method",
        ),
    ]
