# Generated by Django 6.0.6 on 2026-06-28 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0003_2_11'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcetransaction',
            name='source',
        ),
        migrations.RemoveField(
            model_name='sourcetransaction',
            name='djstripe_owner_account',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.DeleteModel(
            name='SourceTransaction',
        ),
    ]
