# Generated by Django 2.2 on 2020-01-20 12:49

from django.db import migrations

import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0005_2_2"),
    ]

    operations = [
        migrations.RemoveField(model_name="invoice", name="closed",),
        migrations.RemoveField(model_name="invoice", name="forgiven",),
        migrations.RemoveField(model_name="upcominginvoice", name="closed",),
        migrations.RemoveField(model_name="upcominginvoice", name="forgiven",),
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=djstripe.fields.StripeEnumField(
                blank=True,
                default="",
                enum=djstripe.enums.InvoiceStatus,
                help_text="The status of the invoice, one of draft, open, paid, uncollectible, or void.",
                max_length=13,
            ),
        ),
        migrations.AddField(
            model_name="upcominginvoice",
            name="status",
            field=djstripe.fields.StripeEnumField(
                blank=True,
                default="",
                enum=djstripe.enums.InvoiceStatus,
                help_text="The status of the invoice, one of draft, open, paid, uncollectible, or void.",
                max_length=13,
            ),
        ),
    ]
