# Generated by Django 2.2.11 on 2020-05-07 19:13

from django.db import migrations, models
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0006_2_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=djstripe.fields.StripeDecimalCurrencyAmountField(decimal_places=2, default=0, help_text='Amount (as decimal) to be charged on the interval specified.', max_digits=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='nickname',
            field=models.TextField(default='', help_text='A brief description of the plan, hidden from customers.', max_length=5000),
        ),
    ]
