# Generated by Django 2.2.2 on 2019-07-09 15:18

from django.db import migrations, models
import django.db.models.deletion
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0006_auto_20190705_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('djstripe_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('id', djstripe.fields.StripeIdField(max_length=255, unique=True)),
                ('livemode', models.NullBooleanField(default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.')),
                ('created', djstripe.fields.StripeDateTimeField(blank=True, help_text='The datetime this object was created in stripe.', null=True)),
                ('metadata', djstripe.fields.JSONField(blank=True, help_text='A set of key/value pairs that you can attach to an object. It can be useful for storing additional information about an object in a structured format.', null=True)),
                ('description', models.TextField(blank=True, help_text='A description of this object.', null=True)),
                ('djstripe_created', models.DateTimeField(auto_now_add=True)),
                ('djstripe_updated', models.DateTimeField(auto_now=True)),
                ('biling_address_collection', models.CharField(blank=True, help_text='The value (auto or required) for whether Checkoutcollected the customer’s billing address.', max_length=255, null=True)),
                ('cancel_url', models.CharField(blank=True, help_text='The URL the customer will be directed to if theydecide to cancel payment and return to your website.', max_length=255, null=True)),
                ('client_reference_id', models.CharField(blank=True, help_text='A unique string to reference the Checkout Session.This can be a customer ID, a cart ID, or similar, andcan be used to reconcile the session with your internal systems.', max_length=255, null=True)),
                ('customer_email', models.CharField(blank=True, help_text='If provided, this value will be used when the Customer object is created.', max_length=255, null=True)),
                ('display_items', djstripe.fields.JSONField(blank=True, help_text='The line items, plans, or SKUs purchased by the customer.', null=True)),
                ('locale', models.CharField(blank=True, help_text='The IETF language tag of the locale Checkout is displayed in.If blank or auto, the browser’s locale is used.', max_length=255, null=True)),
                ('payment_method_types', djstripe.fields.JSONField(help_text='The list of payment method types (e.g. card) that this Checkout Session is allowed to accept.')),
                ('submit_type', models.CharField(blank=True, help_text='Describes the type of transaction being performed by Checkoutin order to customize relevant text on the page, such as the submit button.', max_length=255, null=True)),
                ('success_url', models.CharField(blank=True, help_text='The URL the customer will be directed to after the payment or subscriptioncreation is successful.', max_length=255, null=True)),
                ('customer', models.ForeignKey(help_text='ID of the Customer this Checkout is for if one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.Customer')),
                ('payment_intent', models.ForeignKey(help_text='The ID of the PaymentIntent created if SKUs or line items were provided.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.PaymentIntent')),
                ('subscription', models.ForeignKey(help_text='The ID of the subscription created if one or more plans were provided.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.Subscription')),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
