# Generated by Django 2.2 on 2019-12-12 14:34

import djstripe.enums
import djstripe.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0007_auto_20191107_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='reason',
            field=djstripe.fields.StripeEnumField(blank=True, default='', enum=djstripe.enums.RefundReason, help_text='Reason for the refund.', max_length=25),
        ),
    ]
