# Generated by Django 3.1.3 on 2020-11-19 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0007_2_4"),
    ]

    operations = [
        migrations.RemoveField(model_name="subscription", name="tax_percent"),
    ]
