# Generated by Django 3.0.3 on 2020-02-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0007_update_invoice_subscription_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djstripepaymentmethod',
            name='type',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
