# Generated by Django 3.0.5 on 2020-05-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0007_account_payouts_enabled_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="djstripepaymentmethod",
            name="type",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
