# Generated by Django 2.2 on 2019-12-12 14:34

from django.db import migrations

import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0007_auto_20191107_0118"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refund",
            name="reason",
            field=djstripe.fields.StripeEnumField(
                blank=True,
                default="",
                enum=djstripe.enums.RefundReason,
                help_text="Reason for the refund.",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="status",
            field=djstripe.fields.StripeEnumField(
                blank=True,
                enum=djstripe.enums.RefundStatus,
                help_text="Status of the refund.",
                max_length=9,
            ),
        ),
    ]
