# Generated by Django 3.0.2 on 2020-01-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0007_update_invoice_subscription_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="payouts_enabled",
            field=models.BooleanField(
                help_text="Whether Stripe can send payouts to this account", null=True
            ),
        ),
    ]
