# Generated by Django 2.2.2 on 2019-07-15 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0007_session'),
        ('djstripe', '0005_auto_20190710_1023'),
    ]

    operations = [
    ]
