# Generated by Django 3.1.3 on 2020-11-09 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0007_2_4"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="price",
            field=models.ForeignKey(
                help_text="If the invoice item is a proration, the price of the subscription for which the proration was computed.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoiceitems",
                to="djstripe.price",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="plan",
            field=models.ForeignKey(
                help_text="If the invoice item is a proration, the plan of the subscription for which the proration was computed.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="djstripe.plan",
            ),
        ),
    ]
