# Generated by Django 3.1.3 on 2020-12-19 10:37

from django.db import migrations

import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0008_auto_20201119_2218"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="proration_behavior",
            field=djstripe.fields.StripeEnumField(
                blank=True,
                enum=djstripe.enums.SubscriptionProrationBehavior,
                help_text="Determines how to handle prorations when the billing cycle changes (e.g., when switching plans, resetting billing_cycle_anchor=now , or starting a trial), or if an item’s quantity changes.",
                max_length=17,
                null=True,
            ),
        ),
    ]
