# Generated by Django 3.2.4 on 2021-06-17 05:46

from django.db import migrations

import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0008_2_5"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filelink",
            name="expires_at",
            field=djstripe.fields.StripeDateTimeField(
                blank=True, help_text="Time at which the link expires.", null=True
            ),
        ),
    ]
