# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import djstripe.fields
import model_utils.fields
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0001_initial'),
        ('djstripe', '0008_auto_20150806_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(verbose_name='created', editable=False, default=django.utils.timezone.now)),
                ('modified', model_utils.fields.AutoLastModifiedField(verbose_name='modified', editable=False, default=django.utils.timezone.now)),
                ('stripe_id', djstripe.fields.StripeIdField(unique=True, max_length=50)),
                ('livemode', djstripe.fields.StripeNullBooleanField(help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', default=False)),
                ('stripe_timestamp', djstripe.fields.StripeDateTimeField(help_text='The datetime this object was created in stripe.', null=True)),
                ('metadata', djstripe.fields.StripeJSONField(help_text='A set of key/value pairs that you can attach to an object. It can be useful for storing additional information about an object in a structured format.', blank=True, null=True)),
                ('description', djstripe.fields.StripeTextField(help_text='A description of this object.', blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='StripeSource',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(verbose_name='created', editable=False, default=django.utils.timezone.now)),
                ('modified', model_utils.fields.AutoLastModifiedField(verbose_name='modified', editable=False, default=django.utils.timezone.now)),
                ('stripe_id', djstripe.fields.StripeIdField(unique=True, max_length=50)),
                ('livemode', djstripe.fields.StripeNullBooleanField(help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', default=False)),
                ('stripe_timestamp', djstripe.fields.StripeDateTimeField(help_text='The datetime this object was created in stripe.', null=True)),
                ('metadata', djstripe.fields.StripeJSONField(help_text='A set of key/value pairs that you can attach to an object. It can be useful for storing additional information about an object in a structured format.', blank=True, null=True)),
                ('description', djstripe.fields.StripeTextField(help_text='A description of this object.', blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('stripesource_ptr', models.OneToOneField(auto_created=True, primary_key=True, to='djstripe.StripeSource', parent_link=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('djstripe.stripesource',),
        ),
        migrations.AddField(
            model_name='stripesource',
            name='customer',
            field=models.ForeignKey(related_name='sources', null=True, to='djstripe.Customer'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='stripesource',
            name='polymorphic_ctype',
            field=models.ForeignKey(related_name='polymorphic_djstripe.stripesource_set+', null=True, editable=False, to='contenttypes.ContentType'),
            preserve_default=True,
        ),
        migrations.RemoveField(
            model_name='event',
            name='validated_message',
        ),
        migrations.AddField(
            model_name='charge',
            name='account',
            field=models.ForeignKey(related_name='charges', help_text='The account the charge was made on behalf of. Null here indicates that this value was never set.', null=True, to='djstripe.Account'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='charge',
            name='currency',
            field=djstripe.fields.StripeCharField(max_length=3, help_text='Three-letter ISO currency code representing the currency in which the charge was made.', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='charge',
            name='failure_code',
            field=djstripe.fields.StripeCharField(max_length=30, help_text='Error code explaining reason for charge failure if available.', choices=[('invalid_number', 'Invalid Number'), ('invalid_expiry_month', 'Invalid Expiry Month'), ('invalid_expiry_year', 'Invalid Expiry Year'), ('invalid_cvc', 'Invalid Cvc'), ('incorrect_number', 'Incorrect Number'), ('expired_card', 'Expired Card'), ('incorrect_cvc', 'Incorrect Cvc'), ('incorrect_zip', 'Incorrect Zip'), ('card_declined', 'Card Declined'), ('missing', 'Missing'), ('processing_error', 'Processing Error'), ('rate_limit', 'Rate Limit')], null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='charge',
            name='failure_message',
            field=djstripe.fields.StripeTextField(help_text='Message to user further explaining reason for charge failure if available.', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='charge',
            name='fraudulent',
            field=djstripe.fields.StripeBooleanField(help_text='Whether or not this charge was marked as fraudulent.', default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='charge',
            name='livemode',
            field=djstripe.fields.StripeNullBooleanField(help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='charge',
            name='metadata',
            field=djstripe.fields.StripeJSONField(help_text='A set of key/value pairs that you can attach to an object. It can be useful for storing additional information about an object in a structured format.', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='charge',
            name='shipping',
            field=djstripe.fields.StripeJSONField(help_text='Shipping information for the charge', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='charge',
            name='source',
            field=models.ForeignKey(related_name='charges', null=True, to='djstripe.StripeSource'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='charge',
            name='source_stripe_id',
            field=djstripe.fields.StripeIdField(max_length=50, help_text='The payment source id.', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='charge',
            name='source_type',
            field=djstripe.fields.StripeCharField(max_length=20, help_text='The payment source type. If the payment source is supported by dj-stripe, a corresponding model is attached to this Charge via a foreign key matching this field.', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='charge',
            name='status',
            field=djstripe.fields.StripeCharField(max_length=10, help_text='The status of the payment is either ``succeeded`` or ``failed``.', choices=[('succeeded', 'Succeeded'), ('failed', 'Failed')], null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='charge',
            name='transfer',
            field=models.ForeignKey(help_text='The transfer to the destination account (only applicable if the charge was created using the destination parameter).', null=True, to='djstripe.Transfer'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='customer',
            name='account_balance',
            field=djstripe.fields.StripeIntegerField(help_text="Current balance, if any, being stored on the customer's account. If negative, the customer has credit to apply to the next invoice. If positive, the customer has an amount owed that will be added to the next invoice. The balance does not refer to any unpaid invoices; it solely takes into account amounts that have yet to be successfully applied to any invoice. This balance is only taken into account for recurring charges.", null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='customer',
            name='currency',
            field=djstripe.fields.StripeCharField(max_length=3, help_text='The currency the customer can be charged in for recurring billing purposes (subscriptions, invoices, invoice items).', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='customer',
            name='default_source',
            field=models.ForeignKey(related_name='customers', null=True, to='djstripe.StripeSource'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='customer',
            name='delinquent',
            field=djstripe.fields.StripeBooleanField(help_text='Whether or not the latest charge for the customer’s latest invoice has failed.', default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='customer',
            name='description',
            field=djstripe.fields.StripeTextField(help_text='A description of this object.', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='customer',
            name='livemode',
            field=djstripe.fields.StripeNullBooleanField(help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='customer',
            name='metadata',
            field=djstripe.fields.StripeJSONField(help_text='A set of key/value pairs that you can attach to an object. It can be useful for storing additional information about an object in a structured format.', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='customer',
            name='stripe_timestamp',
            field=djstripe.fields.StripeDateTimeField(help_text='The datetime this object was created in stripe.', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=djstripe.fields.StripeTextField(help_text='A description of this object.', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='event',
            name='metadata',
            field=djstripe.fields.StripeJSONField(help_text='A set of key/value pairs that you can attach to an object. It can be useful for storing additional information about an object in a structured format.', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='event',
            name='received_api_version',
            field=djstripe.fields.StripeCharField(max_length=15, help_text='the API version at which the event data was rendered. Blank for old entries only, all new entries will have this value', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='event',
            name='request_id',
            field=djstripe.fields.StripeCharField(max_length=50, help_text="Information about the request that triggered this event, for traceability purposes. If empty string then this is an old entry without that data. If Null then this is not an old entry, but a Stripe 'automated' event with no associated request.", blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='event',
            name='stripe_timestamp',
            field=djstripe.fields.StripeDateTimeField(help_text='The datetime this object was created in stripe.', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=djstripe.fields.StripeTextField(help_text='A description of this object.', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='invoice',
            name='livemode',
            field=djstripe.fields.StripeNullBooleanField(help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='invoice',
            name='metadata',
            field=djstripe.fields.StripeJSONField(help_text='A set of key/value pairs that you can attach to an object. It can be useful for storing additional information about an object in a structured format.', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_timestamp',
            field=djstripe.fields.StripeDateTimeField(help_text='The datetime this object was created in stripe.', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=djstripe.fields.StripeTextField(help_text='A description of this object.', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='plan',
            name='livemode',
            field=djstripe.fields.StripeNullBooleanField(help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='plan',
            name='metadata',
            field=djstripe.fields.StripeJSONField(help_text='A set of key/value pairs that you can attach to an object. It can be useful for storing additional information about an object in a structured format.', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_timestamp',
            field=djstripe.fields.StripeDateTimeField(help_text='The datetime this object was created in stripe.', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='transfer',
            name='livemode',
            field=djstripe.fields.StripeNullBooleanField(help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='transfer',
            name='metadata',
            field=djstripe.fields.StripeJSONField(help_text='A set of key/value pairs that you can attach to an object. It can be useful for storing additional information about an object in a structured format.', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='transfer',
            name='stripe_timestamp',
            field=djstripe.fields.StripeDateTimeField(help_text='The datetime this object was created in stripe.', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='charge',
            name='amount',
            field=djstripe.fields.StripeCurrencyField(help_text='Amount charged.', decimal_places=2, null=True, max_digits=7),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='charge',
            name='amount_refunded',
            field=djstripe.fields.StripeCurrencyField(help_text='Amount refunded (can be less than the amount attribute on the charge if a partial refund was issued).', decimal_places=2, null=True, max_digits=7),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='charge',
            name='captured',
            field=djstripe.fields.StripeBooleanField(help_text='If the charge was created without capturing, this boolean represents whether or not it is still uncaptured or has since been captured.', default=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='charge',
            name='card_kind',
            field=djstripe.fields.StripeCharField(max_length=50, null=True, default=None),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='charge',
            name='card_last_4',
            field=djstripe.fields.StripeCharField(max_length=4, null=True, default=None),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='charge',
            name='customer',
            field=models.ForeignKey(related_name='charges', help_text='The customer associated with this charge.', to='djstripe.Customer'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='charge',
            name='description',
            field=djstripe.fields.StripeTextField(help_text='A description of this object.', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='charge',
            name='disputed',
            field=djstripe.fields.StripeBooleanField(help_text='Whether or not this charge is disputed.', default=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='charge',
            name='fee',
            field=djstripe.fields.StripeCurrencyField(decimal_places=2, null=True, max_digits=7),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='charge',
            name='invoice',
            field=models.ForeignKey(related_name='charges', help_text='The invoice associated with this charge, if it exists.', null=True, to='djstripe.Invoice'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='charge',
            name='paid',
            field=djstripe.fields.StripeBooleanField(help_text='``true`` if the charge succeeded, or was successfully authorized for later capture, ``false`` otherwise.', default=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='charge',
            name='refunded',
            field=djstripe.fields.StripeBooleanField(help_text='Whether or not the charge has been fully refunded. If the charge is only partially refunded, this attribute will still be false.', default=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='charge',
            name='stripe_id',
            field=djstripe.fields.StripeIdField(unique=True, max_length=50),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='charge',
            name='stripe_timestamp',
            field=djstripe.fields.StripeDateTimeField(help_text='The datetime this object was created in stripe.', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='customer',
            name='card_exp_month',
            field=djstripe.fields.StripePositiveIntegerField(null=True, default=None),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='customer',
            name='card_exp_year',
            field=djstripe.fields.StripePositiveIntegerField(null=True, default=None),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='customer',
            name='card_fingerprint',
            field=djstripe.fields.StripeCharField(max_length=200, null=True, default=None),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='customer',
            name='card_kind',
            field=djstripe.fields.StripeCharField(max_length=50, null=True, default=None),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='customer',
            name='card_last_4',
            field=djstripe.fields.StripeCharField(max_length=4, null=True, default=None),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='customer',
            name='stripe_id',
            field=djstripe.fields.StripeIdField(unique=True, max_length=50),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='customer',
            field=models.ForeignKey(help_text='In the event that there is a related customer, this will point to that Customer record', null=True, to='djstripe.Customer'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='livemode',
            field=djstripe.fields.StripeNullBooleanField(help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', default=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='processed',
            field=models.BooleanField(help_text='If validity is performed, webhook event processor(s) may run to take further action on the event. Once these have run, this is set to True.', default=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='stripe_id',
            field=djstripe.fields.StripeIdField(unique=True, max_length=50),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=djstripe.fields.StripeCharField(max_length=250, help_text="Stripe's event description code"),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='valid',
            field=models.NullBooleanField(help_text='Tri-state bool. Null == validity not yet confirmed. Otherwise, this field indicates that this event was checked via stripe api and found to be either authentic (valid=True) or in-authentic (possibly malicious)'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='webhook_message',
            field=djstripe.fields.StripeJSONField(help_text='data received at webhook. data should be considered to be garbage until validity check is run and valid flag is set'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='attempted',
            field=djstripe.fields.StripeNullBooleanField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='attempts',
            field=djstripe.fields.StripePositiveIntegerField(null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='charge',
            field=djstripe.fields.StripeIdField(max_length=50, blank=True, default='', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='closed',
            field=djstripe.fields.StripeBooleanField(default=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=djstripe.fields.StripeDateTimeField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid',
            field=djstripe.fields.StripeBooleanField(default=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='period_end',
            field=djstripe.fields.StripeDateTimeField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='period_start',
            field=djstripe.fields.StripeDateTimeField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='stripe_id',
            field=djstripe.fields.StripeIdField(unique=True, max_length=50),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=djstripe.fields.StripeCurrencyField(decimal_places=2, max_digits=7),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=djstripe.fields.StripeCurrencyField(decimal_places=2, max_digits=7),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='plan',
            name='stripe_id',
            field=djstripe.fields.StripeIdField(unique=True, max_length=50),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='adjustment_count',
            field=djstripe.fields.StripeIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='adjustment_fees',
            field=djstripe.fields.StripeCurrencyField(decimal_places=2, max_digits=7),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='adjustment_gross',
            field=djstripe.fields.StripeCurrencyField(decimal_places=2, max_digits=7),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=djstripe.fields.StripeCurrencyField(decimal_places=2, max_digits=7),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='charge_count',
            field=djstripe.fields.StripeIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='charge_fees',
            field=djstripe.fields.StripeCurrencyField(decimal_places=2, max_digits=7),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='charge_gross',
            field=djstripe.fields.StripeCurrencyField(decimal_places=2, max_digits=7),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='collected_fee_count',
            field=djstripe.fields.StripeIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='collected_fee_gross',
            field=djstripe.fields.StripeCurrencyField(decimal_places=2, max_digits=7),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=djstripe.fields.StripeDateTimeField(help_text='Date the transfer is scheduled to arrive at destination'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='description',
            field=djstripe.fields.StripeTextField(help_text='A description of this object.', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='event',
            field=models.ForeignKey(related_name='transfers', null=True, to='djstripe.Event'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='net',
            field=djstripe.fields.StripeCurrencyField(decimal_places=2, max_digits=7),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='refund_count',
            field=djstripe.fields.StripeIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='refund_fees',
            field=djstripe.fields.StripeCurrencyField(decimal_places=2, max_digits=7),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='refund_gross',
            field=djstripe.fields.StripeCurrencyField(decimal_places=2, max_digits=7),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=djstripe.fields.StripeCharField(max_length=25),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='stripe_id',
            field=djstripe.fields.StripeIdField(unique=True, max_length=50),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='validation_count',
            field=djstripe.fields.StripeIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='validation_fees',
            field=djstripe.fields.StripeCurrencyField(decimal_places=2, max_digits=7),
            preserve_default=True,
        ),
    ]
