# Generated by Django 2.2.4 on 2019-08-22 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("djstripe", "0008_auto_20190817_0053")]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="account",
            field=models.ForeignKey(
                blank=True,
                help_text="The account the charge was made on behalf of. Null here indicates that this value was never set.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bank_account",
                to="djstripe.Account",
            ),
        )
    ]
