# Generated by Django 2.2.2 on 2019-07-22 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0008_merge_20190715_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='pending_setup_intent',
            field=models.ForeignKey(blank=True, help_text='We can use this SetupIntent to collect user authentication when creating a subscription without immediate payment or updating a subscription’s payment method, allowing you to optimize for off-session payments.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setup_intents', to='djstripe.SetupIntent'),
        ),
    ]
