# Generated by Django 3.1a1 on 2020-05-31 04:37

from django.db import migrations

import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0008_djstripepaymentmethod_type_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="purpose",
            field=djstripe.fields.StripeEnumField(
                enum=djstripe.enums.FileUploadPurpose,
                help_text="The purpose of the uploaded file.",
                max_length=35,
            ),
        ),
    ]
