# Generated by Django 3.2.3 on 2021-05-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0008_auto_20201119_2218"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="countryspec",
            name="djstripe_owner_account",
        ),
    ]
