# Generated by Django 3.0 on 2019-12-14 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0008_auto_20191212_1434"),
    ]

    operations = [
        migrations.DeleteModel(name="UpcomingInvoice",),
    ]
