# Generated by Django 3.1.2 on 2020-11-11 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0009_subscription_schedules"),
    ]

    operations = [
        migrations.AddField(
            model_name="payout",
            name="automatic",
            field=models.BooleanField(
                default=False,
                help_text="`true` if the payout was created by an automated payout schedule, and `false` if it was requested manually.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payout",
            name="source_type",
            field=djstripe.fields.StripeEnumField(
                default="bank_account",
                enum=djstripe.enums.PayoutSourceType,
                help_text="The source balance this payout came from.",
                max_length=12,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payout",
            name="failure_balance_transaction",
            field=djstripe.fields.StripeForeignKey(
                blank=True,
                help_text="If the payout failed or was canceled, this will be the balance transaction that reversed the initial balance transaction, and puts the funds from the failed payout back in your balance.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="failure_payouts",
                to="djstripe.balancetransaction",
                to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD,
            ),
        ),
    ]
