# Generated by Django 3.2.4 on 2021-06-22 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations

import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0009_alter_filelink_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationfee",
            name="account",
            field=djstripe.fields.StripeForeignKey(
                default=1,
                help_text="ID of the Stripe account this fee was taken from.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="application_fees",
                to="djstripe.account",
                to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD,
            ),
            preserve_default=False,
        ),
    ]
