# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 03:23
from __future__ import unicode_literals

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0009_auto_20160104_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='delinquent',
            field=djstripe.fields.StripeBooleanField(default=False, help_text=b'Whether or not the latest charge for the customer\xe2\x80\x99s latest invoice has failed.'),
        ),
    ]
