# Generated by Django 3.2.4 on 2021-08-08 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations

import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0010b_alter_transfer_destination_data_1"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="destination",
            field=djstripe.fields.StripeForeignKey(
                help_text="ID of the Stripe account the transfer was sent to.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transfers",
                to="djstripe.account",
                to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD,
            ),
        ),
    ]
