# Generated by Django 3.2.4 on 2021-08-08 05:52
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0010c_alter_transfer_schema_change_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer",
            name="old_destination_field",
            field=models.IntegerField(null=True),
        ),
        # runSQL to migrate data from old_destination_field column to transfer.destination_id column
        migrations.RunSQL(
            sql="""
                UPDATE djstripe_transfer
                SET destination_id=old_destination_field
                ;
            """,
            reverse_sql="""
                UPDATE djstripe_transfer
                SET old_destination_field=destination_id
                ;
            """,
        ),
    ]
