# Generated by Django 3.2.4 on 2021-08-08 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0010d_alter_transfer_destination_data_2"),
    ]

    operations = [
        migrations.RemoveField(model_name="transfer", name="old_destination_field"),
    ]
