# Generated by Django 3.2.4 on 2021-08-08 05:52
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0010a_alter_transfer_schema_change_1"),
    ]

    operations = [
        # runSQL to update values in column old_destination_field with ids of account from table djstripe_account
        migrations.RunSQL(
            sql="""
                UPDATE djstripe_transfer
                SET old_destination_field=(SELECT djstripe_id FROM djstripe_account WHERE id=djstripe_transfer.old_destination_field)
                ;
            """,
            reverse_sql="""
                UPDATE djstripe_transfer
                SET old_destination_field=(SELECT id FROM djstripe_account WHERE CAST(djstripe_id AS VARCHAR)=djstripe_transfer.old_destination_field)
                ;
            """,
        ),
    ]
