# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 00:59
from __future__ import unicode_literals

from django.db import migrations

import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0009_auto_20170806_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='idempotency_key',
            field=djstripe.fields.StripeTextField(blank=True, null=True),
        ),
    ]
