# Generated by Django 2.2.2 on 2019-07-25 10:43

from django.db import migrations
import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0009_subscription_pending_setup_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='capture_method',
            field=djstripe.fields.StripeEnumField(enum=djstripe.enums.CaptureMethod, help_text='Capture method of this PaymentIntent, one of automatic or manual.', max_length=9),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='confirmation_method',
            field=djstripe.fields.StripeEnumField(enum=djstripe.enums.ConfirmationMethod, help_text='Confirmation method of this PaymentIntent, one of manual or automatic.', max_length=9),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='setup_future_usage',
            field=djstripe.fields.StripeEnumField(default='off_session', enum=djstripe.enums.IntentUsage, help_text='Indicates that you intend to make future payments with thisPaymentIntent’s payment method.If present, the payment method used with this PaymentIntent canbe attached to a Customer, even after the transaction completes.Use `on_session` if you intend to only reuse the payment methodwhen your customer is present in your checkout flow. Use `off_session`if your customer may or may not be in your checkout flow.Stripe uses `setup_future_usage` to dynamically optimize your payment flow andcomply with regional legislation and network rules. For example,if your customer is impacted by SCA, using `off_session` willensure that they are authenticated while processing this PaymentIntent.You will then be able to make later off-session payments for this customer.', max_length=11),
        ),
        migrations.AlterField(
            model_name='session',
            name='submit_type',
            field=djstripe.fields.StripeEnumField(blank=True, enum=djstripe.enums.SubmitTypeStatus, help_text='Describes the type of transaction being performed by Checkoutin order to customize relevant text on the page, such as the submit button.', max_length=6, null=True),
        ),
    ]
