# Generated by Django 2.2.4 on 2019-08-28 08:44

from django.db import migrations

import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [("djstripe", "0009_auto_20190822_0948")]

    operations = [
        migrations.RenameField(
            model_name="session",
            old_name="biling_address_collection",
            new_name="billing_address_collection",
        ),
        migrations.AddField(
            model_name="session",
            name="mode",
            field=djstripe.fields.StripeEnumField(
                blank=True,
                enum=djstripe.enums.SessionMode,
                help_text="The mode of the Checkout Session, one of payment, setup, or subscription.",
                max_length=12,
                null=True,
            ),
        ),
    ]
