# Generated by Django 3.2.3 on 2021-05-30 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0010_auto_20210523_1439"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FileUpload",
            new_name="File",
        ),
    ]
