# Generated by Django 2.2.4 on 2019-08-28 08:52

from django.db import migrations

import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [("djstripe", "0010_auto_20190828_0844")]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="billing_address_collection",
            field=djstripe.fields.StripeEnumField(
                blank=True,
                enum=djstripe.enums.SessionBillingAddressCollection,
                help_text="The value (auto or required) for whether Checkoutcollected the customer’s billing address.",
                max_length=8,
                null=True,
            ),
        )
    ]
