# Generated by Django 3.2.13 on 2022-05-24 19:18

from django.db import migrations
import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0010_alter_customer_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='billing_reason',
            field=djstripe.fields.StripeEnumField(blank=True, default='', enum=djstripe.enums.InvoiceBillingReason, max_length=38),
        ),
        migrations.AlterField(
            model_name='upcominginvoice',
            name='billing_reason',
            field=djstripe.fields.StripeEnumField(blank=True, default='', enum=djstripe.enums.InvoiceBillingReason, max_length=38),
        ),
    ]
