# Generated by Django 3.1.3 on 2020-11-14 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0010_auto_20201111_1317"),
    ]

    operations = [
        migrations.RenameField(
            model_name="charge",
            old_name="account",
            new_name="on_behalf_of",
        ),
        migrations.AddField(
            model_name="charge",
            name="amount_captured",
            field=djstripe.fields.StripeDecimalCurrencyAmountField(
                decimal_places=2,
                help_text="Amount (as decimal) captured (can be less than the amount attribute on the charge if a partial capture was issued).",
                max_digits=11,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="charge",
            name="application",
            field=models.CharField(
                blank=True,
                help_text="ID of the Connect application that created the charge.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="charge",
            name="application_fee_amount",
            field=djstripe.fields.StripeDecimalCurrencyAmountField(
                blank=True,
                decimal_places=2,
                help_text="The amount (as decimal) of the application fee (if any) requested for the charge.",
                max_digits=11,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="charge",
            name="billing_details",
            field=djstripe.fields.JSONField(
                help_text="Billing information associated with the PaymentMethod at the time of the transaction.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="charge",
            name="calculated_statement_descriptor",
            field=models.CharField(
                default="",
                help_text="The full statement descriptor that is passed to card networks, and that is displayed on your customers’ credit card and bank statements. Allows you to see what the statement descriptor looks like after the static and dynamic portions are combined.",
                max_length=22,
            ),
        ),
        migrations.AddField(
            model_name="charge",
            name="disputed",
            field=models.BooleanField(
                default=False, help_text="Whether the charge has been disputed."
            ),
        ),
        migrations.AddField(
            model_name="charge",
            name="source_transfer",
            field=djstripe.fields.StripeForeignKey(
                help_text="The transfer which created this charge. Only present if the charge came from another Stripe account.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="djstripe.transfer",
                to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD,
            ),
        ),
        migrations.AddField(
            model_name="charge",
            name="statement_descriptor_suffix",
            field=models.CharField(
                blank=True,
                help_text="Provides information about the charge that customers see on their statements. Concatenated with the prefix (shortened descriptor) or statement descriptor that's set on the account to form the complete statement descriptor. Maximum 22 characters for the concatenated descriptor.",
                max_length=22,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="charge",
            name="transfer_data",
            field=djstripe.fields.JSONField(
                blank=True,
                help_text="An optional dictionary including the account to automatically transfer to as part of a destination charge.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="billing_thresholds",
            field=djstripe.fields.JSONField(
                blank=True,
                help_text="Define thresholds at which an invoice will be sent, and the subscription advanced to a new billing period.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionitem",
            name="billing_thresholds",
            field=djstripe.fields.JSONField(
                blank=True,
                help_text="Define thresholds at which an invoice will be sent, and the related subscription advanced to a new billing period.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionschedule",
            name="billing_thresholds",
            field=djstripe.fields.JSONField(
                blank=True,
                help_text="Define thresholds at which an invoice will be sent, and the related subscription advanced to a new billing period.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="charge",
            name="statement_descriptor",
            field=models.CharField(
                blank=True,
                help_text="For card charges, use statement_descriptor_suffix instead. Otherwise, you can use this value as the complete description of a charge on your customers’ statements. Must contain at least one letter, maximum 22 characters.",
                max_length=22,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="charge",
            name="transfer",
            field=djstripe.fields.StripeForeignKey(
                help_text="The transfer to the `destination` account (only applicable if the charge was created using the `destination` parameter).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="djstripe.transfer",
                to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD,
            ),
        ),
        migrations.AlterField(
            model_name="charge",
            name="transfer_group",
            field=models.CharField(
                blank=True,
                help_text="A string that identifies this transaction as part of a group.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="charge",
            name="on_behalf_of",
            field=djstripe.fields.StripeForeignKey(
                help_text="The account (if any) the charge was made on behalf of without triggering an automatic transfer.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charges",
                to="djstripe.account",
                to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD,
            ),
        ),
    ]
