# Generated by Django 3.2.5 on 2021-07-10 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations

import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0010_applicationfee_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="balance_transaction",
            field=djstripe.fields.StripeForeignKey(
                help_text="Balance transaction that describes the impact on your account balance.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disputes",
                to="djstripe.balancetransaction",
                to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="charge",
            field=djstripe.fields.StripeForeignKey(
                help_text="The charge that was disputed",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disputes",
                to="djstripe.charge",
                to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="payment_intent",
            field=djstripe.fields.StripeForeignKey(
                help_text="The PaymentIntent that was disputed",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disputes",
                to="djstripe.paymentintent",
                to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="balance_transactions",
            field=djstripe.fields.JSONField(
                default="[]",
                help_text="List of 0, 1 or 2 Balance Transactions that show funds withdrawn and reinstated to your Stripe account as a result of this dispute.",
            ),
        ),
    ]
