# Generated by Django 4.0.1 on 2022-01-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0012_account_djstripe_owner_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionschedule",
            name="billing_thresholds",
        ),
    ]
