# Generated by Django 2.2.3 on 2019-07-28 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [("djstripe", "0010_auto_20190725_1043")]

	operations = [
		migrations.AddField(
			model_name="charge",
			name="payment_intent",
			field=models.ForeignKey(
				help_text="PaymentIntent associated with this charge, if one exists.",
				null=True,
				on_delete=django.db.models.deletion.SET_NULL,
				related_name="charges",
				to="djstripe.PaymentIntent",
			),
		)
	]
