# Generated by Django 3.2.4 on 2021-06-22 09:48
from django.db import migrations


def transfer_to_destination(apps, schema_editor):

    Transfer = apps.get_model("djstripe", "Transfer")
    Account = apps.get_model("djstripe", "Account")
    for transfer in Transfer.objects.all():
        # can't access custom model methods inside migrations
        # and that is why copied the function
        if transfer.destination:
            try:
                # get the Account object
                account = Account.objects.get(transfer.destination)
                # assign the account object to the destination_fk field
                # and save the updated model.
                transfer.destination_fk = account
                transfer.save()
            except Account.DoesNotExist:
                print(
                    f"Account with id {id} does not exist in the db. Please add it to the db and re-run migrations."
                    "This can be done by running the 'python manage.py djstripe_sync_models Account'"
                )
                raise


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0011_transfer_destination_fk"),
    ]

    operations = [
        migrations.RunPython(transfer_to_destination, migrations.RunPython.noop)
    ]
