# Generated by Django 3.2.13 on 2022-05-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0011_remove_subscriptionschedule_billing_thresholds_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="api_version",
            field=models.CharField(
                blank=True,
                help_text="the API version at which the event data was rendered. Blank for old entries only, all new entries will have this value",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="webhookendpoint",
            name="api_version",
            field=models.CharField(
                blank=True,
                help_text="The API version events are rendered as for this webhook endpoint.",
                max_length=64,
            ),
        ),
    ]
