# Generated by Django 3.0 on 2019-12-15 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0011_auto_20191214_0453"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="latest_invoice",
            field=models.ForeignKey(
                help_text="The most recent invoice this subscription has generated.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="djstripe.Invoice",
            ),
        ),
    ]
