# Generated by Django 3.2.4 on 2021-08-08 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db.migrations.operations import fields
from django.db.models.indexes import Index

import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0012_alter_transfer_schema_change_1"),
    ]

    operations = [
        # runSQL to update values in column old_destination_field with ids of account from table djstripe_account
        migrations.RunSQL(
            sql="""
                UPDATE djstripe_transfer
                SET old_destination_field=djstripe_account.djstripe_id
                FROM djstripe_account
                WHERE djstripe_transfer.old_destination_field=djstripe_account.id
                ;
            """,
            reverse_sql="""
                UPDATE djstripe_transfer
                SET old_destination_field=djstripe_account.id
                FROM djstripe_account
                WHERE djstripe_transfer.old_destination_field=djstripe_account.djstripe_id::varchar
                ;
            """,
        ),
    ]
