# Generated by Django 3.2.4 on 2021-08-08 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db.migrations.operations import fields
from django.db.models.indexes import Index

import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0012_alter_transfer_destination_data_2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transfer",
            name="old_destination_field",
        ),
    ]
