# Generated by Django 2.2.4 on 2019-09-02 17:13

from django.db import migrations

import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [("djstripe", "0011_auto_20190828_0852")]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="card_present",
            field=djstripe.fields.JSONField(
                blank=True,
                help_text="If this is an card_present PaymentMethod, this hash contains details about the Card Present payment method.",
                null=True,
            ),
        )
    ]
