# Generated by Django 3.2.13 on 2022-07-15 08:08

import django.db.models.deletion
from django.db import migrations

import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0011_2_7"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upcominginvoice",
            name="default_source",
            field=djstripe.fields.PaymentMethodForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="upcominginvoices",
                to="djstripe.djstripepaymentmethod",
            ),
        ),
    ]
