# Generated by Django 3.2.4 on 2021-08-08 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db.migrations.operations import fields
from django.db.models.indexes import Index

import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0011_auto_20210710_0434"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer",
            name="destination",
            field=djstripe.fields.StripeIdField(
                help_text="ID of the bank account, card, or Stripe account the transfer was sent to.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.RenameField(
            model_name="transfer",
            old_name="destination",
            new_name="old_destination_field",
        ),
    ]
