# Generated by Django 3.2.4 on 2021-08-08 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db.migrations.operations import fields
from django.db.models.indexes import Index

import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0012_alter_transfer_schema_change_2"),
    ]

    operations = [
        # runSQL to migrate data from old_destination_field column to transfer.destination_id column
        migrations.RunSQL(
            sql="""
                UPDATE djstripe_transfer
                SET destination_id=old_destination_field::bigint
                ;
            """,
            reverse_sql="""
                UPDATE djstripe_transfer
                SET old_destination_field=destination_id::varchar
                ;
            """,
        ),
    ]
