# Generated by Django 3.2.15 on 2022-12-20 14:40

from django.db import migrations, models

import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0012_auto_20221217_0559"),
    ]

    operations = [
        migrations.CreateModel(
            name="DjStripeSyncModelTrack",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    djstripe.fields.StripeEnumField(
                        default="started",
                        enum=djstripe.enums.DjStripeSyncModelTrackStatusType,
                        max_length=9,
                    ),
                ),
                (
                    "strategy",
                    djstripe.fields.StripeEnumField(
                        default="incremental",
                        enum=djstripe.enums.DjStripeSyncModelTrackStrategyType,
                        max_length=12,
                    ),
                ),
                ("djstripe_created", models.DateTimeField(auto_now_add=True)),
                ("djstripe_updated", models.DateTimeField(auto_now=True)),
                (
                    "models_to_sync",
                    models.JSONField(help_text="Names of model instances to sync."),
                ),
                (
                    "instances_not_synced",
                    models.JSONField(
                        blank=True,
                        help_text="Model instances that could not be synced due to errors.",
                        null=True,
                    ),
                ),
                (
                    "api_keys_to_sync",
                    models.JSONField(help_text="API Keys to sync for."),
                ),
                (
                    "stripe_created_dict",
                    models.JSONField(
                        blank=True,
                        help_text="A filter on the model instances based on the object created field. The value can be a string with an integer Unix timestamp, or it can be a dictionary.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "DjStripeSyncModelTrack",
                "ordering": ["-djstripe_created"],
            },
        ),
    ]
