# Generated by Django 3.2.4 on 2021-06-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0012_transfer_to_destination_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transfer",
            name="destination",
        ),
        migrations.RenameField(
            model_name="transfer",
            old_name="destination_fk",
            new_name="destination",
        ),
    ]
