# Generated by Django 3.2.12 on 2022-03-29 06:49

from django.db import migrations

from sql.utils import get_sql_for_connection


def forwards_func(apps, schema_editor):
    vendor, sql_statement = get_sql_for_connection(schema_editor, "forward")
    with schema_editor.connection.cursor() as cursor:
        if vendor == "sqlite":
            cursor.executescript(sql_statement)
        else:
            cursor.execute(sql_statement)


def reverse_func(apps, schema_editor):
    vendor, sql_statement = get_sql_for_connection(schema_editor, "backward")
    with schema_editor.connection.cursor() as cursor:
        if vendor == "sqlite":
            cursor.executescript(sql_statement)
        else:
            cursor.execute(sql_statement)


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0012_auto_20221217_0559"),
    ]
    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
