# Generated by Django 3.2.14 on 2022-08-22 16:34

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0012_alter_upcominginvoice_default_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_amount_decimal',
            field=djstripe.fields.StripeDecimalCurrencyAmountField(blank=True, decimal_places=12, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='amount_decimal',
            field=djstripe.fields.StripeDecimalCurrencyAmountField(blank=True, decimal_places=12, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='unit_amount_decimal',
            field=djstripe.fields.StripeDecimalCurrencyAmountField(blank=True, decimal_places=12, max_digits=24, null=True),
        ),
    ]
