# Generated by Django 2.2.4 on 2019-09-03 02:30

from django.db import migrations

import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [("djstripe", "0012_auto_20190902_1713")]

    operations = [
        migrations.AlterField(
            model_name="charge",
            name="fraud_details",
            field=djstripe.fields.JSONField(
                blank=True,
                help_text="Hash with information on fraud assessments for the charge.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="charge",
            name="outcome",
            field=djstripe.fields.JSONField(
                blank=True,
                help_text="Details about whether or not the payment was accepted, and why.",
                null=True,
            ),
        ),
    ]
