# Generated by Django 3.0.7 on 2020-06-11 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0012_apikey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="secret",
            field=models.CharField(
                max_length=128,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^(pk|sk|rk)_(test|live)_([a-zA-Z0-9]{24,99})"
                    )
                ],
            ),
        ),
    ]
