# Generated by Django 3.2.11 on 2022-01-31 17:27

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0012_auto_20220202_1646"),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='applies_to',
            field=djstripe.fields.JSONField(blank=True, null=True),
        ),
    ]
