# Generated by Django 3.2.15 on 2022-12-21 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations

import djstripe.fields


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0012_auto_20221217_0559"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="default_price",
            field=djstripe.fields.StripeForeignKey(
                blank=True,
                help_text="The default price this product is associated with.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="djstripe.price",
                to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD,
            ),
        ),
    ]
