# Generated by Django 3.2.4 on 2021-06-22 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations

import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0013_rename_destination_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer",
            name="destination",
            field=djstripe.fields.StripeForeignKey(
                help_text="ID of the Stripe account the transfer was sent to.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transfers",
                to="djstripe.account",
                to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD,
            ),
        ),
    ]
