# Generated by Django 4.1.6 on 2023-05-11 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0013_2_8a"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("djstripe_created", models.DateTimeField(auto_now_add=True)),
                ("djstripe_updated", models.DateTimeField(auto_now=True)),
                (
                    "djstripe_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("id", djstripe.fields.StripeIdField(max_length=255, unique=True)),
                (
                    "livemode",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text="Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.",
                        null=True,
                    ),
                ),
                ("created", djstripe.fields.StripeDateTimeField(blank=True, null=True)),
                (
                    "open",
                    models.BooleanField(help_text="If true, the review needs action."),
                ),
                (
                    "reason",
                    djstripe.fields.StripeEnumField(
                        enum=djstripe.enums.ReviewReasons, max_length=17
                    ),
                ),
                (
                    "billing_zip",
                    models.CharField(
                        help_text="The ZIP or postal code of the card used, if applicable.",
                        max_length=255,
                    ),
                ),
                (
                    "closed_reason",
                    djstripe.fields.StripeEnumField(
                        enum=djstripe.enums.ReviewClosedReasons, max_length=17
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="The IP address where the payment originated.",
                        null=True,
                    ),
                ),
                (
                    "ip_address_location",
                    djstripe.fields.JSONField(blank=True, null=True),
                ),
                (
                    "opened_reason",
                    djstripe.fields.StripeEnumField(
                        enum=djstripe.enums.ReviewOpenedReasons, max_length=6
                    ),
                ),
                ("session", djstripe.fields.JSONField(blank=True, null=True)),
                (
                    "charge",
                    djstripe.fields.StripeForeignKey(
                        blank=True,
                        help_text="The charge associated with this review.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="djstripe.charge",
                        to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD,
                    ),
                ),
                (
                    "djstripe_owner_account",
                    djstripe.fields.StripeForeignKey(
                        blank=True,
                        help_text="The Stripe Account this object belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="djstripe.account",
                        to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD,
                    ),
                ),
                (
                    "payment_intent",
                    djstripe.fields.StripeForeignKey(
                        blank=True,
                        help_text="The PaymentIntent ID associated with this review, if one exists.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="djstripe.paymentintent",
                        to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD,
                    ),
                ),
            ],
            options={
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
    ]
