# Generated by Django 4.1.6 on 2023-05-10 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0013_2_8a"),
    ]

    operations = [
        migrations.CreateModel(
            name="EarlyFraudWarning",
            fields=[
                ("djstripe_created", models.DateTimeField(auto_now_add=True)),
                ("djstripe_updated", models.DateTimeField(auto_now=True)),
                (
                    "djstripe_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("id", djstripe.fields.StripeIdField(max_length=255, unique=True)),
                (
                    "livemode",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text="Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.",
                        null=True,
                    ),
                ),
                ("created", djstripe.fields.StripeDateTimeField(blank=True, null=True)),
                (
                    "actionable",
                    models.BooleanField(
                        help_text="An EFW is actionable if it has not received a dispute and has not been fully refunded. You may wish to proactively refund a charge that receives an EFW, in order to avoid receiving a dispute later."
                    ),
                ),
                (
                    "fraud_type",
                    djstripe.fields.StripeEnumField(
                        enum=djstripe.enums.EarlyFraudWarningFraudTypes, max_length=27
                    ),
                ),
                (
                    "charge",
                    djstripe.fields.StripeForeignKey(
                        blank=True,
                        help_text="ID of the charge this early fraud warning is for, optionally expanded.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="early_fraud_warnings",
                        to="djstripe.charge",
                        to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD,
                    ),
                ),
                (
                    "djstripe_owner_account",
                    djstripe.fields.StripeForeignKey(
                        blank=True,
                        help_text="The Stripe Account this object belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="djstripe.account",
                        to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD,
                    ),
                ),
                (
                    "payment_intent",
                    djstripe.fields.StripeForeignKey(
                        blank=True,
                        help_text="ID of the Payment Intent this early fraud warning is for, optionally expanded.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="early_fraud_warnings",
                        to="djstripe.paymentintent",
                        to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD,
                    ),
                ),
            ],
            options={
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
    ]
