# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 23:56
from __future__ import unicode_literals

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0013_remove_card_stripe_id_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='country',
            field=djstripe.fields.StripeCharField(help_text='Two-letter ISO code representing the country of the card.', max_length=2, null=True),
        ),
    ]
