# Generated by Django 3.2.9 on 2021-11-11 11:51

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0013_auto_20210817_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookeventtrigger',
            name='stripe_trigger_account',
            field=djstripe.fields.StripeForeignKey(blank=True, help_text='The Stripe Account this object belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
    ]
