# Generated by Django 4.1.6 on 2023-05-12 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations

import djstripe.fields


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0013_2_8a"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verificationreport",
            name="description",
        ),
        migrations.RemoveField(
            model_name="verificationreport",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="verificationsession",
            name="description",
        ),
        migrations.AddField(
            model_name="verificationreport",
            name="verification_session",
            field=djstripe.fields.StripeForeignKey(
                blank=True,
                help_text="ID of the VerificationSession that created this report.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="djstripe.verificationsession",
                to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD,
            ),
        ),
        migrations.AddField(
            model_name="verificationsession",
            name="options",
            field=djstripe.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="verificationsession",
            name="last_verification_report",
            field=djstripe.fields.StripeForeignKey(
                blank=True,
                help_text="ID of the most recent VerificationReport. Learn more about accessing detailed verification results.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="djstripe.verificationreport",
                to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD,
            ),
        ),
    ]
