# Generated by Django 2.2.4 on 2019-09-06 20:13

from django.db import migrations

import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [("djstripe", "0013_auto_20190903_0230")]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=djstripe.fields.StripeEnumField(
                enum=djstripe.enums.SubscriptionStatus,
                help_text="The status of this subscription.",
                max_length=18,
            ),
        )
    ]
