# Generated by Django 4.1.6 on 2023-05-24 13:09

from django.db import migrations

import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0013_2_8a"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookendpoint",
            name="validation",
            field=djstripe.fields.StripeEnumField(
                default="verify_signature",
                enum=djstripe.enums.WebhookEndpointValidation,
                max_length=16,
            ),
        ),
    ]
