# Generated by Django 3.2.15 on 2022-09-22 12:43

from django.db import migrations

import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0014_auto_20220822_1642"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="business_type",
            field=djstripe.fields.StripeEnumField(
                blank=True, default="", enum=djstripe.enums.BusinessType, max_length=17
            ),
        ),
    ]
