# Generated by Django 3.2.9 on 2021-11-27 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0013_auto_20210817_0604'),
    ]

    operations = [

        # runSQL to migrate null data in balance column to default of 0
        migrations.RunSQL(
            sql=migrations.RunSQL.noop,
            reverse_sql="""
                UPDATE djstripe_customer
                SET balance=0
                WHERE balance IS NULL
                ;
            """,
        ),

        # runSQL to migrate null data in delinquent column to default of False
        migrations.RunSQL(
            sql=migrations.RunSQL.noop,
            reverse_sql="""
                UPDATE djstripe_customer
                SET delinquent=False
                WHERE delinquent IS NULL
                ;
            """,
        ),

    ]
