# Generated by Django 3.1.2 on 2020-11-16 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations

import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0014_auto_20201115_2231"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentmethod",
            name="description",
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="alipay",
            field=djstripe.fields.JSONField(
                blank=True,
                help_text="Additional information for payment methods of type `alipay`",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="au_becs_debit",
            field=djstripe.fields.JSONField(
                blank=True,
                help_text="Additional information for payment methods of type `au_becs_debit`",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="bacs_debit",
            field=djstripe.fields.JSONField(
                blank=True,
                help_text="Additional information for payment methods of type `bacs_debit`",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="bancontact",
            field=djstripe.fields.JSONField(
                blank=True,
                help_text="Additional information for payment methods of type `bancontact`",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="eps",
            field=djstripe.fields.JSONField(
                blank=True,
                help_text="Additional information for payment methods of type `eps`",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="fpx",
            field=djstripe.fields.JSONField(
                blank=True,
                help_text="Additional information for payment methods of type `fpx`",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="giropay",
            field=djstripe.fields.JSONField(
                blank=True,
                help_text="Additional information for payment methods of type `giropay`",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="ideal",
            field=djstripe.fields.JSONField(
                blank=True,
                help_text="Additional information for payment methods of type `ideal`",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="interac_present",
            field=djstripe.fields.JSONField(
                blank=True,
                help_text="Additional information for payment methods of type `interac_present`",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="oxxo",
            field=djstripe.fields.JSONField(
                blank=True,
                help_text="Additional information for payment methods of type `oxxo`",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="p24",
            field=djstripe.fields.JSONField(
                blank=True,
                help_text="Additional information for payment methods of type `p24`",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="sepa_debit",
            field=djstripe.fields.JSONField(
                blank=True,
                help_text="Additional information for payment methods of type `sepa_debit`",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="sofort",
            field=djstripe.fields.JSONField(
                blank=True,
                help_text="Additional information for payment methods of type `sofort`",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="card",
            field=djstripe.fields.JSONField(
                blank=True,
                help_text="Additional information for payment methods of type `card`",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="card_present",
            field=djstripe.fields.JSONField(
                blank=True,
                help_text="Additional information for payment methods of type `card_present`",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="customer",
            field=djstripe.fields.StripeForeignKey(
                blank=True,
                help_text="Customer to which this PaymentMethod is saved. This will not be set when the PaymentMethod has not been saved to a Customer.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_methods",
                to="djstripe.customer",
                to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD,
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="type",
            field=djstripe.fields.StripeEnumField(
                enum=djstripe.enums.PaymentMethodType,
                help_text="The type of the PaymentMethod.",
                max_length=15,
            ),
        ),
    ]
