# Generated by Django 3.2.9 on 2021-11-27 08:30

from django.db import migrations, models
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0015_alter_paymentmethod_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, help_text='Whether the Customer instance has been deleted upstream in Stripe or not.', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=djstripe.fields.StripeQuantumCurrencyAmountField(blank=True, default=0, help_text="Current balance (in cents), if any, being stored on the customer's account. If negative, the customer has credit to apply to the next invoice. If positive, the customer has an amount owed that will be added to the next invoice. The balance does not refer to any unpaid invoices; it solely takes into account amounts that have yet to be successfully applied to any invoice. This balance is only taken into account for recurring billing purposes (i.e., subscriptions, invoices, invoice items).", null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='delinquent',
            field=models.BooleanField(blank=True, default=False, help_text="Whether or not the latest charge for the customer's latest invoice has failed.", null=True),
        ),
    ]
