# Generated by Django 3.0.7 on 2020-06-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0014_price"),
    ]

    operations = [
        migrations.RemoveField(model_name="subscription", name="start",),
    ]
