# Generated by Django 2.2.4 on 2019-09-08 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("djstripe", "0014_auto_20190906_2013")]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="default_payment_method",
            field=models.ForeignKey(
                blank=True,
                help_text="default payment method used for subscriptions and invoices for the customer.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="djstripe.PaymentMethod",
            ),
        )
    ]
