# Generated by Django 3.2.16 on 2023-01-26 14:47

import django.db.models.deletion
from django.db import migrations

import djstripe.fields


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0015_alter_payout_destination"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payout",
            name="destination",
            field=djstripe.fields.PaymentMethodForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="djstripe.djstripepaymentmethod",
            ),
        ),
    ]
