# Generated by Django 3.2.15 on 2022-12-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0012_alter_account_business_type"),
        ("djstripe", "0015_alter_account_business_type"),
    ]

    operations = []
