# Generated by Django 3.2.9 on 2021-12-12 08:06

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0015_alter_customer_data_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='latest_invoice',
            field=djstripe.fields.StripeForeignKey(blank=True, help_text='The most recent invoice this subscription has generated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='djstripe.invoice', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
    ]
