# Generated by Django 3.2.13 on 2022-05-25 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0016_270b'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('djstripe_created', models.DateTimeField(auto_now_add=True)),
                ('djstripe_updated', models.DateTimeField(auto_now=True)),
                ('djstripe_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('id', djstripe.fields.StripeIdField(max_length=255, unique=True)),
                ('livemode', models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True)),
                ('created', djstripe.fields.StripeDateTimeField(blank=True, null=True)),
                ('metadata', djstripe.fields.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='A description of this object.', null=True)),
                ('amount_subtotal', djstripe.fields.StripeQuantumCurrencyAmountField()),
                ('amount_total', djstripe.fields.StripeQuantumCurrencyAmountField()),
                ('application', models.CharField(blank=True, help_text='ID of the Connect application that created the Order, if any.', max_length=255)),
                ('automatic_tax', djstripe.fields.JSONField()),
                ('billing_details', djstripe.fields.JSONField(blank=True, null=True)),
                ('client_secret', models.TextField(help_text='The client secret of this PaymentIntent. Used for client-side retrieval using a publishable key.', max_length=5000)),
                ('currency', djstripe.fields.StripeCurrencyCodeField(max_length=3)),
                ('discounts', djstripe.fields.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='A recent IP address of the purchaser used for tax reporting and tax location inference.', null=True)),
                ('line_items', djstripe.fields.JSONField()),
                ('payment', djstripe.fields.JSONField()),
                ('shipping_cost', djstripe.fields.JSONField(blank=True, null=True)),
                ('shipping_details', djstripe.fields.JSONField(blank=True, null=True)),
                ('status', djstripe.fields.StripeEnumField(enum=djstripe.enums.OrderStatus, max_length=10)),
                ('tax_details', djstripe.fields.JSONField(blank=True, null=True)),
                ('total_details', djstripe.fields.JSONField()),
                ('customer', djstripe.fields.StripeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.customer', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD)),
                ('djstripe_owner_account', djstripe.fields.StripeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD)),
                ('payment_intent', djstripe.fields.StripeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.paymentintent', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD)),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
