# Generated by Django 4.1.4 on 2022-12-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0012_auto_20221217_0559"),
        ("djstripe", "0016_merge_20221215_0635"),
    ]

    operations = []
