# Generated by Django 2.2.4 on 2019-09-09 11:23

from django.db import migrations, models

import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [("djstripe", "0016_auto_20190909_1002")]

    operations = [
        migrations.AddField(
            model_name="charge",
            name="payment_method_details",
            field=djstripe.fields.JSONField(
                blank=True,
                help_text="Details about the payment method at the time of the transaction.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="charge",
            name="receipt_url",
            field=models.TextField(
                blank=True,
                default="",
                help_text="This is the URL to view the receipt for this charge. The receipt is kept up-to-date to the latest state of the charge, including any refunds. If the charge is for an Invoice, the receipt will be stylized as an Invoice receipt.",
                max_length=5000,
            ),
        ),
    ]
