# Generated by Django 2.2.4 on 2019-09-10 07:59

from django.db import migrations

import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [("djstripe", "0017_auto_20190909_1123")]

    operations = [
        migrations.AlterField(
            model_name="paymentintent",
            name="cancellation_reason",
            field=djstripe.fields.StripeEnumField(
                blank=True,
                default="",
                enum=djstripe.enums.PaymentIntentCancellationReason,
                help_text="Reason for cancellation of this PaymentIntent, either user-provided (duplicate, fraudulent, requested_by_customer, or abandoned) or generated by Stripe internally (failed_invoice, void_invoice, or automatic).",
                max_length=21,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="setupintent",
            name="cancellation_reason",
            field=djstripe.fields.StripeEnumField(
                blank=True,
                default="",
                enum=djstripe.enums.SetupIntentCancellationReason,
                help_text="Reason for cancellation of this SetupIntent, one of abandoned, requested_by_customer, or duplicate",
                max_length=21,
            ),
            preserve_default=False,
        ),
    ]
