# Generated by Django 2.0.1 on 2018-01-10 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0017_auto_20180110_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='stripe_timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='stripe_timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='charge',
            old_name='stripe_timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='stripe_timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='stripe_timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='dispute',
            old_name='stripe_timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='stripe_timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='stripe_timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='stripe_timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='payout',
            old_name='stripe_timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='stripe_timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='stripe_timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='stripe_timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='stripe_timestamp',
            new_name='created',
        ),
    ]
