# Generated by Django 3.2.13 on 2022-05-27 17:42

from django.db import migrations

import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0017_auto_20220524_1836"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charge",
            name="amount",
            field=djstripe.fields.StripeQuantumCurrencyAmountField(),
        ),
        migrations.AlterField(
            model_name="charge",
            name="amount_captured",
            field=djstripe.fields.StripeQuantumCurrencyAmountField(null=True),
        ),
        migrations.AlterField(
            model_name="charge",
            name="amount_refunded",
            field=djstripe.fields.StripeQuantumCurrencyAmountField(),
        ),
        migrations.AlterField(
            model_name="charge",
            name="application_fee_amount",
            field=djstripe.fields.StripeQuantumCurrencyAmountField(
                blank=True, null=True
            ),
        ),
    ]
