# Generated by Django 3.2.13 on 2022-05-27 16:36

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0017_auto_20220524_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=djstripe.fields.StripeQuantumCurrencyAmountField(),
        ),
    ]
