# Generated by Django 3.2.13 on 2022-07-09 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations

import djstripe.fields


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0018_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="discount",
            field=djstripe.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="discounts",
            field=djstripe.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="upcominginvoice",
            name="discounts",
            field=djstripe.fields.JSONField(blank=True, null=True),
        ),
    ]
