# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 00:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import djstripe.models


DJSTRIPE_SUBSCRIBER_MODEL = getattr(settings, "DJSTRIPE_SUBSCRIBER_MODEL", settings.AUTH_USER_MODEL)


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0018_field_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='subscriber',
            field=models.OneToOneField(null=True, on_delete=djstripe.models.on_subscriber_delete_purge_customers, to=DJSTRIPE_SUBSCRIBER_MODEL),
        ),
    ]
