# Generated by Django 4.1.6 on 2023-03-07 06:17

from django.db import migrations

import djstripe.fields


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0019_add_customer_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="unit_amount_decimal",
            field=djstripe.fields.StripeDecimalCurrencyAmountField(
                blank=True, decimal_places=12, max_digits=20, null=True
            ),
        ),
    ]
