# Generated by Django 4.1.6 on 2023-03-01 06:38

from django.db import migrations

import djstripe.fields


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0019_add_customer_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="line_items",
            field=djstripe.fields.JSONField(blank=True, null=True),
        ),
    ]
