# Generated by Django 2.2.5 on 2019-09-10 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("djstripe", "0019_auto_20190910_0827")]

    operations = [
        migrations.AddField(
            model_name="charge",
            name="payment_method",
            field=models.ForeignKey(
                help_text="PaymentMethod used in this charge.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="charges",
                to="djstripe.PaymentMethod",
            ),
        )
    ]
