# Generated by Django 4.1.6 on 2023-03-06 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0019_add_customer_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="line_items",
            field=djstripe.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="setup_intent",
            field=djstripe.fields.StripeForeignKey(
                blank=True,
                help_text="The ID of the SetupIntent for Checkout Sessions in setup mode.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="djstripe.setupintent",
                to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="shipping_address_collection",
            field=djstripe.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="shipping_cost",
            field=djstripe.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="shipping_details",
            field=djstripe.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="shipping_options",
            field=djstripe.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="amount_subtotal",
            field=djstripe.fields.StripeQuantumCurrencyAmountField(
                blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="amount_total",
            field=djstripe.fields.StripeQuantumCurrencyAmountField(
                blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="url",
            field=models.TextField(
                blank=True,
                help_text="The URL to the Checkout Session. Redirect customers to this URL to take them to Checkout. If you’re using Custom Domains, the URL will use your subdomain. Otherwise, it’ll use checkout.stripe.com. This value is only present when the session is active.",
                max_length=5000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="total_details",
            field=djstripe.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="currency",
            field=djstripe.fields.StripeCurrencyCodeField(
                blank=True, max_length=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="payment_status",
            field=djstripe.fields.StripeEnumField(
                blank=True,
                enum=djstripe.enums.SessionPaymentStatus,
                max_length=19,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="status",
            field=djstripe.fields.StripeEnumField(
                blank=True, enum=djstripe.enums.SessionStatus, max_length=8, null=True
            ),
        ),
    ]
