# Generated by Django 4.1.6 on 2023-03-01 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations

import djstripe.fields


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0020_session_line_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="setup_intent",
            field=djstripe.fields.StripeForeignKey(
                blank=True,
                help_text="The ID of the SetupIntent for Checkout Sessions in setup mode.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="djstripe.setupintent",
                to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD,
            ),
        ),
    ]
