# Generated by Django 3.1.3 on 2020-11-08 19:06

from django.db import migrations, models
import django.db.models.deletion
import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0020_auto_20201108_1534"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="price",
            options={"ordering": ["unit_amount"]},
        ),
        migrations.RemoveField(
            model_name="price",
            name="aggregate_usage",
        ),
        migrations.RemoveField(
            model_name="price",
            name="transform_usage",
        ),
        migrations.RemoveField(
            model_name="price",
            name="trial_period_days",
        ),
        migrations.AddField(
            model_name="price",
            name="lookup_key",
            field=models.CharField(
                blank=True,
                help_text="A lookup key used to retrieve prices dynamically from a static string.",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="transform_quantity",
            field=djstripe.fields.JSONField(
                blank=True,
                help_text="Apply a transformation to the reported usage or set quantity before computing the amount billed. Cannot be combined with `tiers`.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionitem",
            name="price",
            field=models.ForeignKey(
                blank=True,
                help_text="The price the customer is subscribed to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_items",
                to="djstripe.price",
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="billing_scheme",
            field=djstripe.fields.StripeEnumField(
                blank=True,
                enum=djstripe.enums.BillingScheme,
                help_text="Describes how to compute the price per period. Either `per_unit` or `tiered`. `per_unit` indicates that the fixed amount (specified in `unit_amount` or `unit_amount_decimal`) will be charged per unit in `quantity` (for prices with `usage_type=licensed`), or per unit of total usage (for prices with `usage_type=metered`). `tiered` indicates that the unit pricing will be computed using a tiering strategy as defined using the `tiers` and `tiers_mode` attributes.",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="recurring",
            field=djstripe.fields.JSONField(
                blank=True,
                default=None,
                help_text="The recurring components of a price such as `interval` and `usage_type`.",
                null=True,
            ),
        ),
    ]
