# Generated by Django 3.2.11 on 2022-01-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0020_alter_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="valid",
            field=models.BooleanField(
                blank=True,
                help_text="Taking account of the above properties, whether this coupon can still be applied to a customer.",
                null=True,
            ),
        ),
    ]
