# Generated by Django 4.1.6 on 2023-03-30 03:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0021_alter_idempotencykey_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together=set(),
        ),
    ]
