# Generated by Django 4.1.6 on 2023-03-01 07:13

from django.db import migrations

import djstripe.fields


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0021_session_setup_intent"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="shipping_address_collection",
            field=djstripe.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="shipping_cost",
            field=djstripe.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="shipping_details",
            field=djstripe.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="shipping_options",
            field=djstripe.fields.JSONField(blank=True, null=True),
        ),
    ]
