# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 09:37
from __future__ import (
    absolute_import, division, print_function, unicode_literals
)

from django.conf import settings
from django.db import migrations, models


DJSTRIPE_SUBSCRIBER_MODEL = getattr(settings, "DJSTRIPE_SUBSCRIBER_MODEL", settings.AUTH_USER_MODEL)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djstripe', '0022_fix_subscriber_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='subscriber',
            field=models.ForeignKey(null=True, on_delete=models.SET_NULL, related_name='djstripe_customers', to=DJSTRIPE_SUBSCRIBER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set([('subscriber', 'livemode')]),
        ),
    ]
