# Generated by Django 4.1.6 on 2023-03-01 07:24

from django.db import migrations

import djstripe.fields


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0022_session_shipping_address_collection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="amount_subtotal",
            field=djstripe.fields.StripeQuantumCurrencyAmountField(
                blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="amount_total",
            field=djstripe.fields.StripeQuantumCurrencyAmountField(
                blank=True, null=True
            ),
        ),
    ]
