# Generated by Django 4.1.6 on 2023-03-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0023_session_amount_subtotal_session_amount_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="url",
            field=models.TextField(
                blank=True,
                help_text="The URL to the Checkout Session. Redirect customers to this URL to take them to Checkout. If you’re using Custom Domains, the URL will use your subdomain. Otherwise, it’ll use checkout.stripe.com. This value is only present when the session is active.",
                max_length=5000,
                null=True,
            ),
        ),
    ]
