# Generated by Django 2.0.5 on 2018-05-27 23:37

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0024_auto_20180527_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing',
            field=djstripe.fields.StripeCharField(choices=[('charge_automatically', 'Charge automatically'), ('send_invoice', 'Send invoice')], default='', help_text='Either `charge_automatically`, or `send_invoice`. When charging automatically, Stripe will attempt to pay this subscription at the end of the cycle using the default source attached to the customer. When sending an invoice, Stripe will email your customer an invoice with payment instructions.', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_cycle_anchor',
            field=djstripe.fields.StripeDateTimeField(help_text='Determines the date of the first full invoice, and, for plans with `month` or `year` intervals, the day of the month for subsequent invoices.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='days_until_due',
            field=djstripe.fields.StripeIntegerField(help_text='Number of days a customer has to pay invoices generated by this subscription. This value will be `null` for subscriptions where `billing=charge_automatically`.', null=True),
        ),
    ]
