# Generated by Django 4.1.6 on 2023-03-01 14:04

from django.db import migrations

import djstripe.fields


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0024_session_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="total_details",
            field=djstripe.fields.JSONField(blank=True, null=True),
        ),
    ]
