# Generated by Django 4.1.6 on 2023-03-01 14:11

from django.db import migrations

import djstripe.fields


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0025_session_total_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="currency",
            field=djstripe.fields.StripeCurrencyCodeField(
                blank=True, max_length=3, null=True
            ),
        ),
    ]
