# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 13:55
from __future__ import (
    absolute_import, division, print_function, unicode_literals
)

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0025_auto_20170322_0428'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('livemode', models.BooleanField(help_text='Whether the key was used in live or test mode.')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='idempotencykey',
            unique_together=set([('action', 'livemode')]),
        ),
    ]
