# Generated by Django 4.1.6 on 2023-03-01 14:20

from django.db import migrations

import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0026_session_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="payment_status",
            field=djstripe.fields.StripeEnumField(
                blank=True,
                enum=djstripe.enums.SessionPaymentStatus,
                max_length=19,
                null=True,
            ),
        ),
    ]
