# Generated by Django 2.0.5 on 2018-06-04 03:09

from django.db import migrations
import djstripe.fields
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0027_auto_20180528_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_balance',
            field=djstripe.fields.StripeIntegerField(help_text="Current balance, if any, being stored on the customer's account. If negative, the customer has credit to apply to the next invoice. If positive, the customer has an amount owed that will be added to thenext invoice. The balance does not refer to any unpaid invoices; it solely takes into account amounts that have yet to be successfullyapplied to any invoice. This balance is only taken into account for recurring billing purposes (i.e., subscriptions, invoices, invoice items)."),
        ),
        migrations.AlterField(
            model_name='payout',
            name='statement_descriptor',
            field=djstripe.fields.StripeCharField(blank=True, help_text="Extra information about a payout to be displayed on the user's bank statement.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=djstripe.fields.StripeTextField(help_text='Name of the plan, to be displayed on invoices and in the web interface.', null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='statement_descriptor',
            field=djstripe.fields.StripeCharField(blank=True, help_text="Extra information about a source. This will appear on your customer's statement every time you charge the source.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='destination_type',
            field=djstripe.fields.StripeCharField(blank=True, help_text='The type of the transfer destination.', max_length=14, null=True),
        ),
    ]
