# Generated by Django 4.1.6 on 2023-03-01 14:23

from django.db import migrations

import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0027_session_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="status",
            field=djstripe.fields.StripeEnumField(
                blank=True, enum=djstripe.enums.SessionStatus, max_length=8, null=True
            ),
        ),
    ]
