# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-20 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0028_auto_20170313_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='djstripe.Account'),
        ),
    ]
