# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-03 11:00
from __future__ import unicode_literals

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0029_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='livemode',
            field=djstripe.fields.StripeNullBooleanField(default=None, help_text=b'Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.'),
        ),
    ]
