# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 12:05
from __future__ import (
    absolute_import, division, print_function, unicode_literals
)

import django.db.models.deletion
from django.db import migrations, models

import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0029_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.Coupon'),
        ),
        migrations.AddField(
            model_name='customer',
            name='coupon_end',
            field=djstripe.fields.StripeDateTimeField(editable=False, help_text='If a coupon is present and has a limited duration, the date that the discount will end.', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='coupon_start',
            field=djstripe.fields.StripeDateTimeField(editable=False, help_text='If a coupon is present, the date at which it was applied.', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='livemode',
            field=djstripe.fields.StripeNullBooleanField(default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.'),
        ),
    ]
