name: CI tests

on:
  push:
    paths-ignore:
      - "docs/**"
      - "mkdocs.yml"
      - ".readthedocs.yml"
      - ".github/workflows/docs.yml"

  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: djstripe
          POSTGRES_DB: djstripe
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install dependencies
        run: uv sync --group ci

      - name: Test with tox for ${{ matrix.python-version }}
        run: uv run tox
